import Head from "next/head";
import {AiFillLinkedin} from "react-icons/ai";
import Image from "next/image";
import web2 from "./public/web2.png";
import web3 from "./public/web3.png";
import web4 from "./public/web4.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Letícia Reis Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40">
        <section className=  "min-h-screen">
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className="text-xl">LR</h1>
            
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl"> 
            Letícia Reis
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">Engenharia de software</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto">
              Estudante do 4° período de Engenharia de Software e atualmente focando nos estudos de desenvolvimento front-end.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600"> 
          <a href="https://www.linkedin.com/in/letícia-reis-b02a0122b" target="_blank">
            <AiFillLinkedin />
          </a>        
          </div>
        </section>
        
        <section>
         <div>
          <h3 className="text-3xl py-1">Projetos</h3>
          <p className="text-md py-2 leading-8 text-gray-800">
          Aqui estão listados três dos projetos fictícios:
          </p>
         </div>
         <div className=" flex felx-col gap-10 py-10 lg:flex-row lg:flex-wrap">
          <div className="basis-1/3 flex-1">
            <Image src={web2} className="rounded-lg object-cover" 
            width={'100%'} 
            height={"100%"} 
            layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
            <Image src={web3} className="rounded-lg object-cover" 
            width={'100%'} 
            height={"100%"} 
            layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
            <Image src={web4} className="rounded-lg object-cover" 
            width={'100%'} 
            height={"100%"} 
            layout="responsive"/>
            </div>
         </div>
        </section>

        <section>
        <div>
          <h3 className="text-3xl py-1">Contato</h3>
         </div>
            <form class="w-full max-w-lg">
              <div class="flex flex-wrap -mx-3 mb-6">
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                  <label class="block uppercase  py-2 leading-8 tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-first-name">
                    Nome
                  </label>
                  <input class="appearance-none block w-full bg-gray-200 text-gray-700 border py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="grid-first-name" type="text" placeholder="Jane"/>
      
          </div>
            <div class="w-full md:w-1/2 px-3">
              <label class="block uppercase py-2 leading-8 tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-last-name">
                Sobrenome
              </label>
              <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-last-name" type="text" placeholder="Doe"/>
            </div>
          </div>
          <div class="flex flex-wrap -mx-3 mb-6">
            <div class="w-full px-3">
              <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-password">
                E-mail
              </label>
              <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="email" type="email"/>
      
            </div>
          </div>
          <div class="flex flex-wrap -mx-3 mb-6">
            <div class="w-full px-3">
            <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-password">
              Mensagem
            </label>
            <textarea class=" no-resize appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500 h-48 resize-none" id="message"></textarea>
            </div>
          </div>
          <div class="md:flex md:items-center">
            <div class="md:w-1/3">
              <button class="shadow bg-teal-600 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" type="button">
                Enviar
              </button>
            </div>
            <div class="md:w-2/3"></div>
            </div>
            </form>
        </section>
      </main>
    </div>
  )
}
